# Generated by Django 5.2.3 on 2025-11-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_completed_wizard_and_more'),
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wikicategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='wikicategory',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='wikicategory',
            unique_together={('organization', 'name', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='wikipage',
            unique_together={('organization', 'slug')},
        ),
    ]
