runtime: python312 # Or your python version
env: standard
entrypoint: gunicorn -b :$PORT kanban_board.wsgi:application

handlers:
  # This configures Google App Engine to serve static files from the /static/ directory
  - url: /static
    static_dir: staticfiles/ # Or your collected static files directory

  # This handler routes all other requests to your Django app.
  - url: /.*
    script: auto

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic # default value
  min_pending_latency: automatic # default value
  max_pending_latency: automatic # default value
  max_concurrent_requests: 80

# Optional: If you have environment variables to set
env_variables:
  DJANGO_SETTINGS_MODULE: 'kanban_board.settings'
  DEBUG: 'False'
  SECRET_KEY: 'yhj1u7b0_^(b-%5t#n^p!8pzy&%nabpd0*=$7xvfwby&_5_4@c'  # Replace with your actual secret key
  ALLOWED_HOSTS: 'your-app-id.appspot.com,*.appspot.com'
