"""
Check Gemini 2.5 Flash pricing information
"""

print("=" * 70)
print("  GEMINI 2.5 FLASH PRICING INFORMATION")
print("=" * 70)
print()
print("Based on Google AI Studio documentation (as of 2025):")
print()
print("Gemini 2.5 Flash:")
print("  Input:  $0.075 per 1M tokens  ($0.000075 per 1K tokens)")
print("  Output: $0.30 per 1M tokens   ($0.0003 per 1K tokens)")
print()
print("Gemini 1.5 Flash:")
print("  Input:  $0.075 per 1M tokens  ($0.000075 per 1K tokens)")
print("  Output: $0.30 per 1M tokens   ($0.0003 per 1K tokens)")
print()
print("=" * 70)
print("  CONCLUSION")
print("=" * 70)
print()
print("✅ Pricing is THE SAME for both models!")
print()
print("The upgrade from Gemini 1.5 Flash to 2.5 Flash:")
print("  • Same pricing structure")
print("  • Better performance and capabilities")
print("  • More recent training data (June 2025)")
print("  • Improved accuracy and response quality")
print("  • No cost increase!")
print()
print("Our current pricing in analyze_api_costs.py is CORRECT:")
print("  GEMINI_25_FLASH_PRICING = {")
print("      'input_tokens_per_1k': 0.000075,")
print("      'output_tokens_per_1k': 0.0003,")
print("  }")
print()
print("=" * 70)
