# Generated by Django 5.0.1 on 2025-05-31 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_task_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklabel',
            name='category',
            field=models.CharField(choices=[('regular', 'Regular'), ('lean', 'Lean Six Sigma')], default='regular', max_length=20),
        ),
    ]
