# Generated by Django 5.2.3 on 2025-06-18 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_tasklabel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_duration_hours',
            field=models.IntegerField(blank=True, help_text='Actual time spent in hours', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='task',
            name='actual_start_date',
            field=models.DateTimeField(blank=True, help_text='When work actually started', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_recommendations',
            field=models.TextField(blank=True, help_text='AI-generated recommendations for this task', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_risk_score',
            field=models.IntegerField(blank=True, help_text='AI-calculated risk score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='task',
            name='earliest_finish',
            field=models.DateTimeField(blank=True, help_text='AI-calculated earliest finish time', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='earliest_start',
            field=models.DateTimeField(blank=True, help_text='AI-calculated earliest start time', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_duration_hours',
            field=models.IntegerField(default=8, help_text='Estimated time to complete in hours', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_start_date',
            field=models.DateTimeField(blank=True, help_text='AI-suggested or manually set start date', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_critical_path',
            field=models.BooleanField(default=False, help_text='AI-determined: is this task on the critical path?'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_milestone',
            field=models.BooleanField(default=False, help_text='Is this task a project milestone?'),
        ),
        migrations.AddField(
            model_name='task',
            name='last_ai_analysis',
            field=models.DateTimeField(blank=True, help_text='When AI last analyzed this task', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='latest_finish',
            field=models.DateTimeField(blank=True, help_text='AI-calculated latest finish time', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='latest_start',
            field=models.DateTimeField(blank=True, help_text='AI-calculated latest start time', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='predecessors',
            field=models.ManyToManyField(blank=True, help_text='Tasks that must be completed before this task can start', related_name='successors', to='kanban.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='slack_time_hours',
            field=models.IntegerField(blank=True, help_text='AI-calculated slack/float time in hours', null=True),
        ),
    ]
