# Generated by Django 5.2.3 on 2025-06-18 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_add_ai_timeline_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='collaboration_required',
            field=models.BooleanField(default=False, help_text='Does this task require collaboration with others?'),
        ),
        migrations.AddField(
            model_name='task',
            name='complexity_score',
            field=models.IntegerField(default=5, help_text='Task complexity score (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='task',
            name='optimal_assignee_suggestions',
            field=models.JSONField(blank=True, default=list, help_text='AI-suggested optimal assignees with match scores'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_skills',
            field=models.JSONField(blank=True, default=list, help_text="Required skills for this task (e.g., [{'name': 'Python', 'level': 'Intermediate'}])"),
        ),
        migrations.AddField(
            model_name='task',
            name='resource_conflicts',
            field=models.JSONField(blank=True, default=list, help_text='Identified resource conflicts and scheduling issues'),
        ),
        migrations.AddField(
            model_name='task',
            name='skill_match_score',
            field=models.IntegerField(blank=True, help_text='AI-calculated skill match score for assigned user (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='task',
            name='suggested_team_members',
            field=models.JSONField(blank=True, default=list, help_text='AI-suggested team members for collaborative tasks'),
        ),
        migrations.AddField(
            model_name='task',
            name='workload_impact',
            field=models.CharField(choices=[('low', 'Low Impact'), ('medium', 'Medium Impact'), ('high', 'High Impact'), ('critical', 'Critical Impact')], default='medium', help_text="Impact on assignee's workload", max_length=20),
        ),
    ]
