# Generated by Django 5.2.3 on 2025-06-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_meetingtranscript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='actual_duration_hours',
        ),
        migrations.RemoveField(
            model_name='task',
            name='actual_start_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='earliest_finish',
        ),
        migrations.RemoveField(
            model_name='task',
            name='earliest_start',
        ),
        migrations.RemoveField(
            model_name='task',
            name='estimated_duration_hours',
        ),
        migrations.RemoveField(
            model_name='task',
            name='estimated_start_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_critical_path',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_milestone',
        ),
        migrations.RemoveField(
            model_name='task',
            name='latest_finish',
        ),
        migrations.RemoveField(
            model_name='task',
            name='latest_start',
        ),
        migrations.RemoveField(
            model_name='task',
            name='predecessors',
        ),
        migrations.RemoveField(
            model_name='task',
            name='slack_time_hours',
        ),
    ]
