# Generated by Django 5.2.3 on 2025-10-24 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_remove_task_planning_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_risk_assessment',
            field=models.DateTimeField(blank=True, help_text='When AI last performed risk assessment for this task', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='mitigation_suggestions',
            field=models.JSONField(blank=True, default=list, help_text='AI-generated mitigation strategies and action plans'),
        ),
        migrations.AddField(
            model_name='task',
            name='risk_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Complete AI risk analysis including reasoning and factors'),
        ),
        migrations.AddField(
            model_name='task',
            name='risk_impact',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], help_text='Risk impact score (1=Low, 2=Medium, 3=High)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='task',
            name='risk_indicators',
            field=models.JSONField(blank=True, default=list, help_text='Key indicators to monitor for this risk (from AI analysis)'),
        ),
        migrations.AddField(
            model_name='task',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='AI-determined risk level classification', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='risk_likelihood',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], help_text='Risk likelihood score (1=Low, 2=Medium, 3=High)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='task',
            name='risk_score',
            field=models.IntegerField(blank=True, help_text='AI-calculated risk score (Likelihood × Impact, range 1-9)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
