# Generated by Django 5.2.3 on 2025-10-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0025_stakeholder_engagement_tracking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectstakeholder',
            unique_together={('board', 'email', 'name')},
        ),
    ]
