# Generated by Django 5.2.3 on 2025-11-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0027_taskfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(blank=True, help_text='Tasks that must be completed before this task can start', related_name='dependent_tasks', to='kanban.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, help_text='Task start date for Gantt chart', null=True),
        ),
    ]
