# Generated by Django 5.2.3 on 2025-06-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability_schedule',
            field=models.JSONField(blank=True, default=dict, help_text="Weekly availability schedule (e.g., {'monday': {'start': '09:00', 'end': '17:00'}})"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='average_task_completion_time',
            field=models.FloatField(default=0.0, help_text='Average time to complete tasks (in hours)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='collaboration_score',
            field=models.IntegerField(default=100, help_text='Collaboration effectiveness score (0-100)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_workload_hours',
            field=models.IntegerField(default=0, help_text='Currently assigned hours (auto-calculated)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_resource_analysis',
            field=models.DateTimeField(blank=True, help_text="When AI last analyzed this user's resource profile", null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='peak_productivity_hours',
            field=models.JSONField(blank=True, default=list, help_text="Hours when user is most productive (e.g., ['09:00-11:00', '14:00-16:00'])"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_task_types',
            field=models.JSONField(blank=True, default=list, help_text='Preferred types of tasks based on performance history'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='productivity_trend',
            field=models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', help_text='AI-calculated productivity trend', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quality_score',
            field=models.IntegerField(default=100, help_text='Quality score based on rework rates and reviews (0-100)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resource_risk_factors',
            field=models.JSONField(blank=True, default=list, help_text='AI-identified risk factors for this resource'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text="List of skills with proficiency levels (e.g., [{'name': 'Python', 'level': 'Expert'}, {'name': 'React', 'level': 'Intermediate'}])"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_capacity_hours',
            field=models.IntegerField(default=40, help_text='Available working hours per week'),
        ),
    ]
