"""
Management command to test and demonstrate AI caching functionality
"""

from django.core.management.base import BaseCommand
from django.core.cache import cache
from kanban.utils.cache_utils import (
    get_cached_ai_response,
    set_cached_ai_response,
    get_cache_stats,
    create_cache_key
)


class Command(BaseCommand):
    help = 'Test AI caching functionality and display cache statistics'

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Clear all AI caches',
        )
        parser.add_argument(
            '--test',
            action='store_true',
            help='Run cache functionality tests',
        )

    def handle(self, *args, **options):
        if options['clear']:
            self.clear_ai_caches()
        elif options['test']:
            self.test_cache_functionality()
        else:
            self.show_cache_stats()

    def clear_ai_caches(self):
        """Clear all AI-related caches"""
        cache.clear()
        self.stdout.write(
            self.style.SUCCESS('✅ All AI caches cleared successfully!')
        )

    def test_cache_functionality(self):
        """Test basic cache operations"""
        self.stdout.write('🧪 Testing AI cache functionality...\n')
        
        # Test task description caching
        test_title = "Test Task for Caching"
        test_description = "This is a test description generated by AI"
        
        # Set cache
        set_cached_ai_response('task_description', test_description, title=test_title.lower())
        self.stdout.write(f'📝 Cached task description for: "{test_title}"')
        
        # Get from cache
        cached_result = get_cached_ai_response('task_description', title=test_title.lower())
        if cached_result == test_description:
            self.stdout.write(self.style.SUCCESS('✅ Cache SET/GET working correctly!'))
        else:
            self.stdout.write(self.style.ERROR('❌ Cache SET/GET failed!'))
        
        # Test cache key generation
        key1 = create_cache_key('task_description', title='test')
        key2 = create_cache_key('task_description', title='test')
        key3 = create_cache_key('task_description', title='different')
        
        if key1 == key2 and key1 != key3:
            self.stdout.write(self.style.SUCCESS('✅ Cache key generation working correctly!'))
        else:
            self.stdout.write(self.style.ERROR('❌ Cache key generation failed!'))
        
        # Test board analytics caching
        set_cached_ai_response('board_analytics', {'summary': 'Test board summary'}, board_id=1)
        cached_analytics = get_cached_ai_response('board_analytics', board_id=1)
        
        if cached_analytics and cached_analytics.get('summary') == 'Test board summary':
            self.stdout.write(self.style.SUCCESS('✅ Board analytics caching working correctly!'))
        else:
            self.stdout.write(self.style.ERROR('❌ Board analytics caching failed!'))
        
        self.stdout.write('\n🎉 Cache functionality testing completed!')

    def show_cache_stats(self):
        """Display current cache statistics"""
        self.stdout.write('📊 AI Cache Statistics\n' + '='*50)
        
        stats = get_cache_stats()
        
        for key, value in stats.items():
            self.stdout.write(f'{key}: {value}')
        
        # Test some cache keys
        test_keys = [
            ('task_description', {'title': 'example task'}),
            ('board_analytics', {'board_id': 1}),
            ('comments_summary', {'task_id': 1, 'last_comment_time': 1234567890}),
            ('lss_classification', {'title': 'example', 'description': 'test'}),
        ]
        
        self.stdout.write('\n🔍 Sample Cache Keys:')
        for cache_type, kwargs in test_keys:
            key = create_cache_key(cache_type, **kwargs)
            cached_value = cache.get(key)
            status = "HIT" if cached_value else "MISS"
            self.stdout.write(f'{cache_type}: {status}')
        
        self.stdout.write(f'\n💡 To test caching: python manage.py test_ai_cache --test')
        self.stdout.write(f'💡 To clear cache: python manage.py test_ai_cache --clear')
